<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    font-family: DejaVu Sans, Arial, sans-serif;
    font-size: 11px;
    color: #1a1a1a;
    background: #fff;
  }

  /* ── Page header ─────────────────────────────────── */
  .report-header {
    background: #1e3a5f;
    color: #fff;
    padding: 14px 18px 12px;
    margin-bottom: 16px;
  }
  .report-header .brand {
    font-size: 10px;
    letter-spacing: 1px;
    text-transform: uppercase;
    opacity: 0.75;
    margin-bottom: 4px;
  }
  .report-header h1 {
    font-size: 18px;
    font-weight: 700;
    margin-bottom: 4px;
  }
  .report-header .meta {
    font-size: 10px;
    opacity: 0.85;
  }
  .report-header .meta span { margin-right: 18px; }

  /* ── Section headings ────────────────────────────── */
  .section-title {
    background: #2c5282;
    color: #fff;
    padding: 5px 10px;
    font-size: 11px;
    font-weight: 700;
    margin: 14px 0 6px;
    letter-spacing: 0.4px;
  }
  .subsection-title {
    background: #ebf4ff;
    color: #2c5282;
    padding: 4px 10px;
    font-size: 10px;
    font-weight: 700;
    margin: 10px 0 4px;
    border-left: 3px solid #2c5282;
  }

  /* ── Tables ──────────────────────────────────────── */
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 8px;
  }
  th {
    background: #dbeafe;
    color: #1e3a5f;
    font-size: 10px;
    font-weight: 700;
    padding: 5px 8px;
    border: 1px solid #93c5fd;
    text-align: left;
  }
  th.right, td.right { text-align: right; }
  th.center, td.center { text-align: center; }
  td {
    padding: 4px 8px;
    border: 1px solid #d1d5db;
    font-size: 10px;
    vertical-align: top;
  }
  tr:nth-child(even) td { background: #f8fafc; }
  tr:nth-child(odd)  td { background: #ffffff; }

  /* ── Totals row ──────────────────────────────────── */
  .totals-row td {
    background: #1e3a5f !important;
    color: #fff;
    font-weight: 700;
    border-color: #1e3a5f;
  }
  .subtotals-row td {
    background: #dbeafe !important;
    color: #1e3a5f;
    font-weight: 700;
    border-color: #93c5fd;
  }

  /* ── Summary boxes ───────────────────────────────── */
  .summary-grid {
    width: 100%;
    margin: 10px 0;
  }
  .summary-box {
    display: inline-block;
    border: 1px solid #93c5fd;
    background: #eff6ff;
    padding: 8px 14px;
    margin-right: 10px;
    margin-bottom: 6px;
    border-radius: 3px;
  }
  .summary-box .label {
    font-size: 9px;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  .summary-box .value {
    font-size: 14px;
    font-weight: 700;
    color: #1e3a5f;
  }

  /* ── Footer ──────────────────────────────────────── */
  .page-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 22px;
    background: #f1f5f9;
    border-top: 1px solid #cbd5e1;
    font-size: 9px;
    color: #6b7280;
    padding: 4px 18px;
  }
  .page-footer .left  { float: left; }
  .page-footer .right { float: right; }

  /* ── Utility ─────────────────────────────────────── */
  .text-muted   { color: #6b7280; }
  .text-right   { text-align: right; }
  .text-center  { text-align: center; }
  .mb-4         { margin-bottom: 4px; }
  .amount       { font-family: "Courier New", monospace; }
  .badge-in     { color: #065f46; font-weight: 700; }
  .badge-out    { color: #991b1b; font-weight: 700; }
  .no-data      { color: #9ca3af; font-style: italic; padding: 8px; }
  .page-break   { page-break-after: always; }
</style>
</head>
<body>

{{-- Footer on every page --}}
<div class="page-footer">
  <span class="left">Generated by Money Manager &nbsp;&bull;&nbsp; {{ now()->format('d M Y, H:i') }}</span>
  <span class="right">Page <span class="pagenum"></span></span>
</div>

@yield('content')

</body>
</html>
